```{r}
pi <- 3.14
radius <- 5
Circle_Area <- pi * ((radius)^2)
print(Circle_Area)
```

```{r}
num <- 17
if (17 %% 2 == 0){
  print('17 is an even number')
} else{
  print('17 is not an even number')
}

```

```{r}
x <- 5
x <- x+10
print(x)
```

```{r}
x <- 5 #or readline('Enter a number')
y <- 6 #or readline('enter  a second number')

if(x > y){
  print(x ,'is greater than ', y)
} else if (x <= y){
  print(x, 'is less than or equal to ', y)
} 
```

```{r}
age <- readline('Enter your age.')
if (age >= 13 && age <= 19){
  print('You are a teenager')
} else{
  print('You are not a teenager.')
}

```

```{r}
variable <- 'y'

if (variable == 'y' | variable = 'n'){
  print('valid character')
} else {
  print('invalid character')
}

```

```{r}
is_logged_in <- TRUE
print(!is_logged_in)
```

```{r}
list_a <- [1, 2,3]
list_b <- [1, 2, 3]
if (list_a %in% list_b){
  print('Same Object')
} else{
  print('Different object')
}
```

```{r}
list <- [1, 2, 3, 4, 5]
if (5 %in% list){
  print('5 is in the list')
} else {
  print('5 is not in the list')
}
```

```{r}
var <- NULL 

if (is.null(var)){
  print('The variable value in Null')
} else{
  print('The variable has another value')
}
```

```{r}

```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```


```{r}
```

